### ISSUE TITLE
Cannot create SSL/TLS link when retrieving metadata

### ISSUE THREAD

**Issue by cotepatrice** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#108]
When I load the web API (TaskService) project, I get an an SSL error in the OpenIdConnectCachingSecurityTokenProvider class in the RetrieveMetadata when calling my OIDC endpoint. This one is correct as I can copy/paste it to Chrome and I get the metadata. Probably a setting in IIS Express? Like adding a certificate somewhere?

The infamous error : "The request was aborted: Could not create SSL/TLS secure channel."

**Comment by jmprieur** [comment]
Normally the best way is to use .NET FW > 4.7.2

**Comment by cotepatrice** [comment]
@jmprieur seems to work with 4.8 without setting the security protocol. Therefore the team should update the target framework. Usually when we pull a sample projet from GitHub, it's supposed to work without having to change anything but the configuration values.

**Comment by jmprieur** [comment]
Yes, I agree. @cotepatrice 
@aremo-ms. can you please update it?

**Comment by aremo-ms** [comment]
I'm on it

**Comment by aremo-ms** [comment]
@jmprieur 
PR: https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi/pull/110

**Comment by aremo-ms** [comment]
@cotepatrice please verify the solution work for you, we've just merged update.

**Comment by cotepatrice** [comment]
I still have the SSL problem, but it's probably because I'm on a VPN and I already have a workaround. But the update to 4.8 works great. Thanks!

**Comment by jmprieur** [comment]
What is your operating system, @cotepatrice ?
