### ISSUE TITLE
Could not load file or assembly Microsoft.Identity.Client, Version=4.37.0.0

### ISSUE THREAD

**Issue by wikipi** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#116]
When I run on my local macine, I keep getting an error when assigning IConfidentialClientApplication on Startup.Auth.cs file in TaskWebApp project. It says:

`Could not load file or assembly 'Microsoft.Identity.Client, Version=4.37.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

Im using Visual Studio Community 20219, installed .NET 4.8., I have cleaned solution project, deleted packages folder, and rebuild solution. It keeps throwing an error.

When I deploy it to Azure App Service, using Windows OS, Framework ASP V4.8, it says:

`Found conflicts between different versions of the same dependent assembly`

![azureeeeee](https://user-images.githubusercontent.com/70028341/143763963-07dcdab3-5dfb-4eb7-9390-ef776541f481.jpg)

for detail link: https://github.com/wikipi/active-directory-b2c-dotnet-webapp-and-webapi/runs/4344953525?check_suite_focus=true

**Comment by Turbo549** [comment]
I issued pull request #119  to address this and to fix a problem that was occurring when your B2C policy names use mixed case and TasksController.AcquireTokenForScopes() calls were failing to silently acquire a token to access the sample API.
