### ISSUE TITLE
Sign up / Sign in failed

### ISSUE THREAD

**Issue by guobinC** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#118]
I cloned the source code 15 Dec 2021, use VS2019 to build on master branch and run. Without any code change, try to Sign up / Sign in, it reports:

  Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.

![image](https://user-images.githubusercontent.com/45161435/146130742-6d120693-e933-4fa8-95ba-5ef24298ad76.png)

Same error when I tried to use my own B2C instance.

**Comment by guobinC** [comment]
After set breakpoint to 
notification.Response.Redirect("/Home/Error?message=" + notification.Exception.Message);

the detail error message is:

Unable to get authorization code Could not load file or assembly 'Microsoft.Identity.Client, Version=4.37.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040).

**Comment by Turbo549** [comment]
I issued pull request #119 to address this and to fix a problem that was occurring when your B2C policy names use mixed case and TasksController.AcquireTokenForScopes() calls were failing to silently acquire a token to access the sample API.

**Comment by hercul1017** [comment]
I had the same problem and adding "/tfp" to AadInstance parameter in web.config fixed it.

<add key="ida:AadInstance" value="https://parrotexamcom.b2clogin.com/tfp/{0}/{1}" />

I could login, however api call fails now.
 
Account always null, GetAccountAsync could not find account in AcquireTokenForScopes method.

 var account = await cca.GetAccountAsync(ClaimsPrincipal.Current.GetB2CMsalAccountIdentifier());

should new issue be created?
