### ISSUE TITLE
Upgrade to .NET 6 for macOS

### ISSUE THREAD

**Issue by sshquack** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#120]
Trying to clone the sample and couldn't run this since it is pinned to legacy .NET 4.8.

https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi/blob/474c6342bd148092be236a53f4cb9539952c9b82/TaskService/TaskService.csproj#L17

Please upgrade to the .NET 6 so it works on LTS version.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976c73ce-6915-43a0-d862-2c05465341f8
* Version Independent ID: f4f562c1-8a77-4e36-4815-14533492e52d
* Content: [Quickstart: Set up sign-in for an ASP.NET web app - Azure AD B2C](https://docs.microsoft.com/en-ca/azure/active-directory-b2c/quickstart-web-app-dotnet)
* Content Source: [articles/active-directory-b2c/quickstart-web-app-dotnet.md](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/active-directory-b2c/quickstart-web-app-dotnet.md)
* Service: **active-directory**
* Sub-service: **b2c**
* GitHub Login: @kengaderdus
* Microsoft Alias: **kengaderdus**

**Comment by aremo-ms** [comment]
@sshquack can you take a look into [this](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C) sample? 
This is going to be .NET 6.0 LTS

**Comment by sshquack** [comment]
@aremo-ms Yep I am aware of the other repo and I have been using it. But for some reason Google search shows this stale repo higher than the other repo
![Screenshot 000065@2x](https://user-images.githubusercontent.com/5678459/152605477-9242a23c-e375-427b-a3b3-b483250bf4ec.png)

So I would recommend archiving this repo and update the readme to point to the other repo...

**Comment by aremo-ms** [comment]
@sshquack This specific sample is .NET Framework. It cannot be updated to .NET 6
Not sure about Google engine though
Closing the issue here then
