### ISSUE TITLE
Error: Sending the request from Localhost don't work

### ISSUE THREAD

**Issue by rari2012** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#13]
Hi,
i'm working on Win10 with VS 2015 running your sample.
Many thanks for this excellent way of showing how Azure B2C is working to secure an API.

I'm running the example local. I managed to get logging in to the website. But the request will not send because of SSL issues in localhost.

Has anyone a suggest how to fix that?

Many thanks in advance,
regards,
Ralf

**Comment by parakhj** [comment]
There shouldn't be any SSL related issues when it comes to making requests to the API. Could you expand a bit more or provide a screenshot/error?

**Comment by kalelgwapo** [comment]
Hi,

I've downloaded the solution and encountered almost the same issue.

Steps to replicate:

1. Download the solution
2. Opened the solution (adminstrator)
3. Followed the demo steps (multiple start up)
4. Prompted by Visual Studio regarding SSL and IIS Express.
5. Selected OK to all

When browser opens up localhost, error occured.

![image](https://user-images.githubusercontent.com/1221371/31363575-9e624d34-ad91-11e7-8aba-f3b8d56ce5dc.png)

Browser opened up two tabs of localhost with different ports.

Hope this helps.

**Comment by gsacavdm** [comment]
Looks like the website is not running at all... are you seeing any errors anywhere? Anything that helps understand what's going on?

**Comment by TiagoBrenck** [comment]
Closing since we haven't heard back from the developer. Please re-open if still facing the problem.
