### ISSUE TITLE
AuthenticationResult.AccessToken is null in OnAuthorizationCodeReceived

### ISSUE THREAD

**Issue by daniel-leibold** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#16]
Great demo so far.

I`ve configured the app like the walkthrough mentioned but when the OnAuthorizationCodeReceived is called **no AccessToken** will be received (empty).

The Policies are working fine. I can login and change some settings. However accessing the Tasks Service does not work and returns an "Unauthorized" on the screen when clicking on ToDo-List. 

1. When i try to dig into the documentation at [githhub](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/active-directory-b2c/active-directory-b2c-devquickstarts-web-api-dotnet.md) i found inconsitencies. The class **NaiveSessionCache** is not available and the acquireToken-Function of Controllers\TasksController.cs is inlined. 

2. Should the "**App-ID-URI**" end with "Tasks" or "api"? The documentation is somehow misleading. ;-(

Any help would be appreciated!

**Comment by parakhj** [comment]
This sample has two projects inside it (TasksService and TasksWebApp). NaiveSessionCache should be in the TaskWebApp project. The link you gave points to a different project altogether.

The App ID URI should be what you defined it to be in the Azure Portal

**Comment by saraford** [comment]
@daniel-leibold Hi! :wave: I just made some changes to the readme earlier today to provide more step-by-step instructions. Let us know if you're still having any issues. Thanks! 😄

**Comment by TiagoBrenck** [comment]
Closing since we having heard back from the developer. Please re-open if this issue is still occurring.
