### ISSUE TITLE
Sample is broken when upgrading MSAL to v1.1.0 Preview

### ISSUE THREAD

**Issue by PatLac04** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#2]
Since MSAL v1.1.0Preview is now available, I tried updating the sample to use it. The same code that is working with the previous alpha version now fails with:

*AADSTS70011: The provided value for the input parameter 'scope' is not valid. The scope https://mytenant.onmicrosoft.com/tasks/read https://mytenant.onmicrosoft.com/tasks/write offline_access openid profile is not valid.*

The scopes **offline_access** , **openid** and **profile** are added somewhere by MSAL, why?

StackTrace is here:
[stackTrace.txt](https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi/files/987556/stackTrace.txt)

**Comment by NikolaosWakem** [comment]
I agree it would be great to have this example working!!

**Comment by parakhj** [comment]
Thanks for letting us know! I'll investigate and update the sample.

**Comment by NikolaosWakem** [comment]
Ideally a aspnetcore 1.1 working version too would be amazing!

**Comment by PatLac04** [comment]
The problem I was having is related to the fact that the AadInstance is different now. MSAL expect to find **tfp** in it. It's in the source code from the msal_update branch but it still requires multiple changes to work, it's a work in progress.

**Comment by gsacavdm** [comment]
The samples has been updated to work with the latest version of MSAL.
See #3
