### ISSUE TITLE
Works for Demo Env, but not for my B2C

### ISSUE THREAD

**Issue by stokes770** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#22]
I'm able to run the demo environment as expected.

Running against my own B2C tenant, I'm unable to get an AccessToken from AcquireTokenByAuthorizationCodeAsync.   AccessToken is always null.

The glaring difference I can see is that one of my resulting claims are different.

1. The demo environment has the default policy under a claim type "http://schemas.microsoft.com/claims/authnclassreference", while my B2C resulting claim has the default police under a claim type of "tfp"

I've double checked all my web.config, setup, and scopes.
I've deleted and re-added the application on the B2C side and created a fresh user.
Always clearing cookie, same in Chrome and Edge.

No luck.  Any help appreciated.

**Comment by parakhj** [comment]
Not sure what you mean by:

> The demo environment has the default policy under a claim type "http://schemas.microsoft.com/claims/authnclassreference", 

The policy should be under the claim 'tfp'. What did you enter in your scopes?

**Comment by stokes770** [comment]
The claim type was different in the demo vs my own B2C.

Either way, I just figured out the step I missed.  
I hadn't added the new published scopes under API Access.

Thanks for the reply, sorry for the churn.
