### ISSUE TITLE
Integration testing examples.

### ISSUE THREAD

**Issue by DerekChasse** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#23]
Could we please get some examples of writing and running integration tests against Web API's which leverage Azure AD B2C?

The following does a good job describing the general concept of integration testing Web API's, however falls short of testing with authentication enabled not to mention Azure Active Directory B2C.

https://docs.microsoft.com/en-us/aspnet/core/testing/integration-testing

Thank you,
~Derek

**Comment by jennyf19** [comment]
@DerekChasse you can see how we've set up integration tests against a Web API in [microsoft identity web](https://github.com/AzureAD/microsoft-identity-web/tree/master/tests/IntegrationTests) similar would apply to a B2C authority. Feel free to open an issue there if you need more specifics.
