### ISSUE TITLE
Hosting in IIS 7

### ISSUE THREAD

**Issue by pkmahapatra** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#25]
Hello all,
I am using visual studio 2015 and IIS Express for the development and everything works as expected. But when I switch the server to Local IIS (under the properties of TaskWebApp) it starts throwing the following exception -
![image](https://user-images.githubusercontent.com/31986903/35215146-699f0750-ff89-11e7-8b00-dc1a7a932beb.png)

InvalidOperationException: IDX10803: Unable to create to obtain configuration from: 'https://login.microsoftonline.com/tfp/XXXXB2CTenant.onmicrosoft.com/B2C_1_B2C_SignIn/v2.0/.well-known/openid-configuration'.]

What could be the possible reason to this and how to solve it.

Thanks 
Prabhanjan
--

**Comment by jennyf19** [comment]
closing as old issue. feel free to re-open if this is happening w/VS2019. thank you.
