### ISSUE TITLE
Very outdated sample

### ISSUE THREAD

**Issue by onionhammer** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#26]
These samples utilize an older version of Owin/microsoft identitymodel

What's the latest guidance on how to authenticate against B2C from a NON- aspnet core app?

**Comment by vazans** [comment]
@onionhammer , I have also opened the same issue here https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi/issues/28
with more details and getting traction from @parakhj , Please follow that Issue.
Also if you had found a working code, Please update me as well @vazans would be very useful,

**Comment by parakhj** [comment]
Updated the sample. Closing issue
