### ISSUE TITLE
How can we get email on successful authentication using OpenIdConnect?

### ISSUE THREAD

**Issue by immayankmodi** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#31]
I'm using following options for OpenIdConnectAuthenticationOptions object but not getting Email or profile data in success response.

> TokenValidationParameters = new TokenValidationParameters {
>       NameClaimType = "email",
>        SaveSigninToken = true //important to save the token in boostrapcontext
> },
> // Specify the scope by appending all of the scopes requested into one string (seperated by a blank space)
> Scope = $"openid profile email offline_access {ReadTasksScope} {WriteTasksScope}",
> ResponseType = "id_token",
> 

Thanks!

**Comment by TiagoBrenck** [comment]
Yes you can, if you have it checked on your user flow. To do it, please follow [this documentation](https://docs.microsoft.com/en-us/azure/active-directory-b2c/user-flow-custom-attributes).

Note that the claim name in the default user flow is `emails`.

**Comment by jennyf19** [comment]
closing as answered.
