### ISSUE TITLE
Bad Request - Request Too Long HTTP Error 400. The size of the request headers is too long.

### ISSUE THREAD

**Issue by clmyers** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#32]
Upon signing into my tenant I'm receiving:

Bad Request - Request Too Long
HTTP Error 400. The size of the request headers is too long.

There was another issue for this but it was closed due to a feature that was coming soon.  The issue itself has not been resolved and support has said we should open a new ticket.  Thanks!

**Comment by BarbaraSelden** [comment]
has this issue been fixed?

**Comment by TiagoBrenck** [comment]
@BarbaraSelden  We have updates this sample a few weeks ago. 
Could you please double check if you still face the same error @clmyers ?

Thanks

**Comment by TiagoBrenck** [comment]
Closing since we haven't heard back. Please, re-open if the issue persists
