### ISSUE TITLE
Asp.NET Core

### ISSUE THREAD

**Issue by JimBobSquarePants** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#35]
This repo is linked directly from documentation specific to ASP.NET Core.

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c-webapi?view=aspnetcore-2.1

See link **Call a .NET web API from a .NET web app using Azure AD B2C.** below the code sample within **Next Steps** section)

Yet the codebase here is targeting the full NET Framework and legacy MVC. I've yet to find an adequate sample that performs the same functionality as this application but targeting Core. 

Can we get a branch or repo with a more up to date target?

**Comment by GaryTosh** [comment]
Couldn't agree more with this request... really struggling to get this working with .net core 2.1.

Securing the web app is easy.... it's the getting of the access_token to past over to the api that's proving difficult. 

We have managed to get it working using this example https://github.com/chrispadgettlivecom/WebApp-OpenIDConnect-DotNetCore21 but this seems to reinvent the wheel a bit.

**Comment by jondmcelroy** [comment]
It is also pointing to the MSAL 1.1.0-preview library, when we are now up to 2.6.0-preview. Would love for this to get an update.

**Comment by Anduin2017** [comment]
+1. Waitting for .NET Core version.

**Comment by TiagoBrenck** [comment]
@Anduin2017 the sample will be available soon on this repo: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2

**Comment by Anduin2017** [comment]
I got the example 

https://github.com/Azure-Samples/active-directory-b2c-dotnetcore-webapp

**Comment by TiagoBrenck** [comment]
Please, refer to this .NET Core sample: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C

**Comment by jennyf19** [comment]
closing, as @TiagoBrenck has linked above the current b2c sample.
