### ISSUE TITLE
Verbosity for ID claims match not sufficient

### ISSUE THREAD

**Issue by weznagwama** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#39]
Not really an issue (first github contribution sorry), but when attempting to match `objectidentifier` claim in the api\TasksController.cs, to a JWT where the claim doesn't exist, bombs out with a non-descriptive error.

We can add better error handling/checking here so it's more clear for people new to oath, like me :)

Note: I'm forking and creating a PR around this.

**Comment by jmprieur** [comment]
The commit seems to be merged.
