### ISSUE TITLE
Null token back from AcquireTokenSilentAsync

### ISSUE THREAD

**Issue by NikolaosWakem** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#4]
make sure you don't use custom domains.. only xxx.onmicrosoft.com

**Comment by gsacavdm** [comment]
Update to the readme with instructions on this are coming, adding @parakhj for visibility.
The UI is available, we just need to add those steps. Adding @parakhj for visibility.

In short, you need to [register scopes for your web API](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-app-registration#register-a-web-api) and then [grant permissions to your Web API to those scopes](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-access-tokens#granting-permissions-to-a-web-api)

**Comment by NikolaosWakem** [comment]
Don't suppose you could give me a screenshot of the current setup of 

Tenant: fabrikamb2c.onmicrosoft.com
Application: fdb91ff5-5ce6-41f3-bdbd-8267c817015d

I have tried to configure this numerous times from without success on my B2C :-(

![image](https://cloud.githubusercontent.com/assets/4430381/26070457/a7f68360-399c-11e7-8665-ce9e087a4f80.png)

![image](https://cloud.githubusercontent.com/assets/4430381/26070490/cc116d6e-399c-11e7-8006-f221961205ec.png)

![image](https://cloud.githubusercontent.com/assets/4430381/26070501/d7cd9d76-399c-11e7-8410-513db75b0fca.png)

![image](https://cloud.githubusercontent.com/assets/4430381/26070562/f5758014-399c-11e7-9553-54195c4634ce.png)

**Comment by NikolaosWakem** [comment]
I setup an 2 x applications - 

application 1) "TaskWebApp"
application 2) "TaskService"

is that ok? ... 

![image](https://cloud.githubusercontent.com/assets/4430381/26071915/b6c598f4-39a1-11e7-91b5-01a0ce7e38e9.png)

i have this on the TaskService (api)

![image](https://cloud.githubusercontent.com/assets/4430381/26071957/ce2b775c-39a1-11e7-9e05-7f4c3c444f3a.png)

![image](https://cloud.githubusercontent.com/assets/4430381/26071977/d763f1dc-39a1-11e7-8876-cd7f96416634.png)

and this on TaskwebApp

![image](https://cloud.githubusercontent.com/assets/4430381/26071995/eb5b5482-39a1-11e7-88a8-b1e4f882788a.png)

**Comment by parakhj** [comment]
Everything looks right... you get the code as well. You get a null token after you do the exchange?

**Comment by NikolaosWakem** [comment]
I get this during login

![image](https://cloud.githubusercontent.com/assets/4430381/26072501/9e48d424-39a3-11e7-9284-261cb36121e2.png)

and this when i click the task list button on GUI

![image](https://cloud.githubusercontent.com/assets/4430381/26072533/be505f26-39a3-11e7-9510-cf60a1a103a4.png)

**Comment by parakhj** [comment]
This might be a caching issue. Could you open a different browser (private if necessary) and try using that? If it still fails, let me know.

**Comment by NikolaosWakem** [comment]
new PC... different location..

![image](https://cloud.githubusercontent.com/assets/4430381/26075541/938e0928-39ad-11e7-840f-5f24da1458cf.png)

![image](https://cloud.githubusercontent.com/assets/4430381/26075764/5671d79e-39ae-11e7-9be0-4d6d059e7347.png)

chrome with incognito

![image](https://cloud.githubusercontent.com/assets/4430381/26075633/df2f436a-39ad-11e7-8f46-41675b7bf19f.png)

same problem sadly

![image](https://cloud.githubusercontent.com/assets/4430381/26075655/f3aaf870-39ad-11e7-961e-ad5e7da31476.png)

**Comment by gsacavdm** [comment]
Did you also update your UseOpenIdConnectAuthentication setup, [Startup.Auth.cs#L85](https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi/blob/master/TaskWebApp/App_Start/Startup.Auth.cs#L85)?

**Comment by NikolaosWakem** [comment]
same result on published version sadly

![image](https://cloud.githubusercontent.com/assets/4430381/26076277/25538886-39b0-11e7-80ba-80f558bfb742.png)

**Comment by NikolaosWakem** [comment]
@gsacavdm yes, runing the latest code from this repo
![image](https://cloud.githubusercontent.com/assets/4430381/26076427/a3c36524-39b0-11e7-953a-bbb3e5524a01.png)

**Comment by NikolaosWakem** [comment]
basically I just took the demo app.. make these changes and hit run.

<add key="ida:Tenant" value="identity.tradeteq.com" />
<add key="ida:ClientId" value="7a5416dd-cfeb-4d92-89ee-9845826dbf6d" />
<add key="ida:ClientSecret" value="fo1o:f3z7?[9s%E~" />
<add key="api:ApiIdentifier" value="https://identity.tradeteq.com/tasks/" />

**Comment by parakhj** [comment]
Could you try removing all of the scopes other than ReadTasksScope and WriteTasksScope? It should return an error and hopefully the error message can give us some insight. I'll look into our logs in the meantime and see if I can find something

Parakh

**Comment by NikolaosWakem** [comment]
with

![image](https://cloud.githubusercontent.com/assets/4430381/26077415/d9d210e0-39b3-11e7-8c20-2df68f77f8d1.png)

just get

![image](https://cloud.githubusercontent.com/assets/4430381/26077406/d192e666-39b3-11e7-9ffb-43bc05ad74ed.png)

**Comment by allenhula** [comment]
Using same B2C tenant and same steps, this sample code works, but my asp.net core code doesn't work, always return NULL access token. Posted question on stackoverflow: [](http://stackoverflow.com/questions/43970669/failed-to-get-accesstoken-via-authorization-code-using-msal-1-1-0-preview-in-asp)
I checked the fiddler trace and found no different on the token request with authorization code.

**Comment by allenhula** [comment]
I do found one difference, the process. This sample code is iisexpress, but my asp.net core is dotnet. Weird thing is I did debug my web app as IISEXPRESS. Does this matter?
![image](https://cloud.githubusercontent.com/assets/20550718/26092771/5d47570a-3a45-11e7-9404-b051940de077.png)

**Comment by allenhula** [comment]
Provide more information of the request when using asp.net core in case needed:

> POST https://login.microsoftonline.com/hulab2c.onmicrosoft.com/oauth2/v2.0/token?p=b2c_1_signuporsignin HTTP/1.1
> Connection: Keep-Alive
> Content-Type: application/x-www-form-urlencoded
> Accept: application/json
> Accept-Encoding: gzip, deflate
> Cookie: x-ms-gateway-slice=001-000; stsservicecookie=cpim_te; x-ms-cpim-slice=001-000; x-ms-cpim-dc=HKG
> x-client-SKU: MSAL.CoreCLR
> x-client-Ver: 1.1.0.0
> x-client-OS: Microsoft Windows 10.0.15063 
> client-request-id: f349f9dd-62b4-42c5-b1f3-6072a19f507f
> return-client-request-id: true
> Content-Length: 1132
> Host: login.microsoftonline.com
> 
> client_id=7f865ca0-271e-4f27-be21-6f0072fe3ad7

**Comment by NikolaosWakem** [comment]
I reckon MSAL needs a 'debug' mode or a 'throw exceptions' mode where it returns info about the problem/error, not just null in AccessToken.. The Sample code should check for 'null' in the AccessToken IMHO and not just blindly create the AuthenticationHeaderValue object if this is 'by design' behavior.

**Comment by parakhj** [comment]
@allenhula  your client ID's look different:

client_id=7f865ca0-271e-4f27-be21-6f0072fe3ad7
client_id=b1e7f41a-f4be-4f80-9519-18294f084221

Can you double check its configured correctly?

**Comment by parakhj** [comment]
@NikolaosWakem 

Can you post your feedback as an issue in the MSAL library repo?

**Comment by allenhula** [comment]
@parakhj I registered different clients in B2C tenant separately for the sample code and my asp.net core project. So that's expected. 

To be more clear, below are my topology:

Tenant: hulab2c.onmicrosoft.com
Sample code project registration:
- Web App client id: b1e7f41a-f4be-4f80-9519-18294f084221
- Web Api id url: https://hulab2c.onmicrosoft.com/tasks (published scopes are read, write)
My asp.net core project registration:
- Web App client id: 7f865ca0-271e-4f27-be21-6f0072fe3ad7
- Web Api id url: https://hulab2c.onmicrosoft.com/b2cdemo (published scope is all)

I am sure all API Access are configured correctly.

**Comment by allenhula** [comment]
@parakhj I see there is a client-request-id in the get token request, is it able to use it to check on server side for detailed failure reason?
My asp.net core project request: 
> client-request-id: f349f9dd-62b4-42c5-b1f3-6072a19f507f

**Comment by NikolaosWakem** [comment]
@allenhula please let me know if you get the .net 4.5 or .netcore 1.1 working against your own B2C.. I need .aspnetcore to work for my codebase, but can't even get the 4.5 demo app to work on my B2C

**Comment by allenhula** [comment]
@NikolaosWakem my .net 4.5 works very well using the sample code as I stated before. Just .netcore doesn't work. I guess our failure reason is different.

**Comment by NikolaosWakem** [comment]
There is a .netcore version here https://github.com/Azure-Samples/active-directory-b2c-dotnetcore-webapp but i get same problem on both :-(

**Comment by allenhula** [comment]
I Finally found out my failure reason: the request to get AuthorizationCode doesn't contain the target scope. Reflect in code, for OpenIdConnectOption in aspnetcore, the Scope parameter is readonly and its default value is "opened profile". 
![image](https://cloud.githubusercontent.com/assets/20550718/26239903/a17d622a-3cb1-11e7-897d-787a29dd8280.png)
The authorization code request sent:

> GET https://login.microsoftonline.com/hulab2c.onmicrosoft.com/oauth2/v2.0/authorize?p=b2c_1_signuporsignin&client_id=7f865ca0-271e-4f27-be21-6f0072fe3ad7&redirect_uri=https%3A%2F%2Flocalhost%3A44355%2Fsignin-oidc&response_type=code%20id_token&scope=openid%20profile&response_mode=form_post&nonce=...... HTTP/1.1

Thus, using this authorization code in response to get token, even we set right scope in the token request, we still can't get the access code but only id token, because the provide authorization code is only for "openid profile".

To fix this, we need to add target web api scope into the authorization code as well. Here is the how-to code:
```
Events = new OpenIdConnectEvents
 {
                    OnRedirectToIdentityProvider = context =>
                    {
                        context.ProtocolMessage.Scope += $" offline_access https://hulab2c.onmicrosoft.com/tasks/read";

                        return Task.FromResult(0);
                    },
                    ......
}
```

In AspNet, we don't need to do this because its scope is not readonly as aspnetcore and can be set directly:
```
new OpenIdConnectAuthenticationOptions
{
               ......
               Scope = $"openid profile offline_access {ReadTasksScope} {WriteTasksScope}"
}
```

**Comment by allenhula** [comment]
@NikolaosWakem Suggest you to use Fiddler to capture the request and check what's missing in your environment.
