### ISSUE TITLE
httpContext.Session is null in MSALSessionCache.Load

### ISSUE THREAD

**Issue by ShannonHaas** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#44]
I have successfully setup the sample with my own Tenant. It is working well. When I create my own project from scratch and replicate every single thing down to the exact same dll's, it fails to reproduce the same results as the sample did. It fails when trying to Deserialize the HttpContext.Session within the MSALSessoCache Class, Load method. If I comment out the deserialize I can see that I am getting the token back with the proper information and claims. The deserialization results in a null object exception when casting to blob. Because I can see the user info and the fact that it works in the sample, I am assuming the Azure Tenant is correct.

I created the new MVC application with "No Authentication" , changed to HTTPS as well as updated the Project Url in properties. Copied the code over verifying the OWIN Startup.cs class and Startup.Auth.cs. Everything is identical with exception to the https redirect url and https TaskServiceUrl within the web.config. I have also verified that the proper https url has been added in the tenants application. setup with Azure B2C. Am I missing something?

**Comment by asmithKinegdo** [comment]
I have the exact same issue.  When converting a project that already had aspnet auth it worked fine, but starting from scratch and adding to a project fails in MSALSessionCache load

**Comment by asmithKinegdo** [comment]
Just figured out that using msal 2.0 preview was causing my issues.  This cost me days of work!

**Comment by ShannonHaas** [comment]
Hi @asmithKinegdo, are you referring to the Microsoft.Identity.Client dll. I originally had mine at the 2.0 prerelease and I downgraded to 1.1.4.0 version and no luck. What exact version did you downgrade to. It appears that the original sample is running 1.1.0.0

**Comment by ShannonHaas** [comment]
@asmithKinegdo Looks like downgrading to Microsoft.Identity.Client dll version 1.1.0.0 did the trick. I do not know about 1.1.1.0, 1.1.2.0, or 1.1.3.0... already wasted days with this one. Thank you @asmithKinegdo

**Comment by parakhj** [comment]
Apologies for the inconvenience. This is a known issue: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/604

**Comment by ShannonHaas** [comment]
@parakhj I did see #604 and it is the reason I downgraded to 1.1.4.0. It did not work until I went to 1.1.0.0.

**Comment by IyyappanAmirthalingam** [comment]
Downgrading  Microsoft.Identity.Client dll version to 1.1.0.0  is also giving the Session Null with .Net 4.7.2 Framework.

**Comment by dustynl** [comment]
Hey @IyyappanAmirthalingam ... did you find a solution to the Session Null issue yet? I'm having the exact same problem. Also lost more than a day already :(

**Comment by parakhj** [comment]
@jennyf19 and @jmprieur  is there something in addition that needs to be done in 2.6>

**Comment by jmprieur** [comment]
cc: @henrik-me (ASP.NET session perturbated by MSAL)
@parakhj : I'll try to have a look, but won't be before Tuesday next week.

**Comment by asmithKinegdo** [comment]
I'm still having this issue with 2.6, as well,  I have a asp.net identity project that I converted and that project won't even work with 1.1.4.0

**Comment by blfuentes** [comment]
@asmithKinegdo Thanks! that was exactly my problem also...

**Comment by tmarinov** [comment]
I am still having the issue of missing Session in MSALSessionCache 
(Microsoft.Identity.Client 2.7.1).
In fact, Session is null  in the "context" input parameter of OnAuthorizationCodeReceivedContext.
I don't use SignalR.

**Comment by tmarinov** [comment]
Ok, the problem was on my side - wrong order of adding the middleware in the startup file.

**Comment by TiagoBrenck** [comment]
Closing since they found a solution.
