### ISSUE TITLE
Azure B2C built in policies - Bad request

### ISSUE THREAD

**Issue by dkchittimilla** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#46]
Hi Team,

Currently we are using Azure B2C built in policies for signin, signup and logout. Sometimes, while navigating to these pages, we are getting "Bad request" and application getting down. Can you please guide me on how to handle this situation.
Below is the URL we captured in browser network.

https://login.microsoftonline.com/xxxx.xxxx.com/B2C_1_DEV_SignIn/api/CombinedSigninAndSignup/confirmed?csrf_token=bGVPaG5JbzFwU1BIV1o3MHBtZ24xU2VBdlFoYWsyNkVDbHdTOXVGUVhicHJUQVpnQTBsWEJzN2pyQ1MwaThsTDljQjY5VUVUMmh4R2crcmNtMDVEeFE9PTsyMDE4LTExLTA4VDE4OjA3OjE0LjgzNjQ3NDdaO05aOFg4THBlc3lnejZoNnVZME85aWc9PTt7Ik9yY2hlc3RyYXRpb25TdGVwIjoxfQ==&tx=StateProperties=eyJUSUQiOiJiOThhNTI3MS1iZTE3LTRiMmMtOWE0My04ZTdkMjAzZDhiYzMifQ&p=B2C_1_DEV_SignIn&diags=%7B%22pageViewId%22%3A%22d79b1c9c-f67f-46fb-8e0b-0703f626ff99%22%2C%22pageId%22%3A%22CombinedSigninAndSignup%22%2C%22trace%22%3A%5B%7B%22ac%22%3A%22T005%22%2C%22acST%22%3A1541700435%2C%22acD%22%3A3%7D%2C%7B%22ac%22%3A%22T021%20-%20URL%3Ahttps%3A%2F%2Fsidentity.blob.core.windows.net%2Fb2c-container-dev%2FTT.CustomPages%2Funified.html%22%2C%22acST%22%3A1541700435%2C%22acD%22%3A16%7D%2C%7B%22ac%22%3A%22T029%22%2C%22acST%22%3A1541700435%2C%22acD%22%3A29%7D%2C%7B%22ac%22%3A%22T004%22%2C%22acST%22%3A1541700435%2C%22acD%22%3A24%7D%2C%7B%22ac%22%3A%22T019%22%2C%22acST%22%3A1541700435%2C%22acD%22%3A66%7D%2C%7B%22ac%22%3A%22T003%22%2C%22acST%22%3A1541700435%2C%22acD%22%3A79%7D%2C%7B%22ac%22%3A%22T030Online%22%2C%22acST%22%3A0%2C%22acD%22%3A0%7D%2C%7B%22ac%22%3A%22T018%22%2C%22acST%22%3A1541700606%2C%22acD%22%3A4758%7D%2C%7B%22ac%22%3A%22T002%22%2C%22acST%22%3A0%2C%22acD%22%3A0%7D%5D%7D

**Comment by jennyf19** [comment]
@dkchittimilla apologies for not getting to this sooner. are you still having the issue? if you give us your b2c tenant, we can try to help.
Also, in the b2c portal you can run the policies directly and make sure they are working properly. 

Going to close, as this issue is pretty old, but please reopen if you need help (please tag me). Thanks.

**Comment by boylec** [comment]
I am currently experiencing this same issue.

However, it only occurs when running tests from automated tests (cypress)

When I login using chrome by hand w/ same account and everything I do not get a Bad Request response.
