### ISSUE TITLE
This B2C quick-start/tutorial implementation is not correct aligned with Set redirect URLs to b2clogin.com for Azure Active Directory B2C

### ISSUE THREAD

**Issue by becke-ch-s0-v1** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#48]
Hi, the b2c quick-start/tutorial implementation see "https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-quickstarts-web-app" respective download here "https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi/archive/master.zip" is not correct aligned and still using "login.microsoftonline.com" see https://docs.microsoft.com/en-us/azure/active-directory-b2c/b2clogin
See: active-directory-b2c-dotnet-webapp-and-webapi-master\TaskService\Web.config
    <add key="ida:AadInstance" value="https://login.microsoftonline.com/{0}/v2.0/.well-known/openid-configuration?p={1}" />
See: active-directory-b2c-dotnet-webapp-and-webapi-master\TaskWebApp\Web.config
    <add key="ida:AadInstance" value="https://login.microsoftonline.com/tfp/{0}/{1}/v2.0/.well-known/openid-configuration" />
I hope this should soon get fixed?
Thank you

**Comment by kodubeau** [comment]
Following. We are having trouble updating an application to use AzureAD-Multi that was based on the download.

**Comment by kodubeau** [comment]
I've tried updating the code myself to use b2clogin.com.

Updated TaskWebApp web.config:
Line 21 <add key="ida:AadInstance" value="https://kokomatics.b2clogin.com/tfp/{0}/{1}" />
Updated TaskWebService web.config:
Line 15 <add key="ida:AadInstance" value="https://kokomatics.b2clogin.com/{0}/v2.0/.well-known/openid-configuration?p={1}" />
Updated Global.bs
Line 34 
public static string WellKnownMetadata = $"https://login.windows.net/kokomatics.onmicrosoft.com/v2.0/.well-known/openid-configuration";

Currently receiving error code:
AADSTS50020: User account '<user account>' from identity provider 'https://sts.windows.net/<guid>/' does not exist in tenant 'kokomatics' and cannot access the application '<Application ClientID>'(App Name) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.

**Comment by mmacy** [comment]
Hello @becke-ch-s0-v1 and @kodubeau. Both this code sample the associated tutorials have been updated to b2clogin.com, and also have a fix for _user logout_ and the _To-Do List_ when using your own tenant (see #60). I've confirmed the docs and this sample, when used together, to be functional in their current state. Thank you so much for your patience while we got this sorted.

* [Tutorial: Enable authentication in a web application using Azure Active Directory B2C](https://docs.microsoft.com/azure/active-directory-b2c/active-directory-b2c-tutorials-web-app)
* [Tutorial: Grant access to an ASP.NET web API using Azure Active Directory B2C](https://docs.microsoft.com/azure/active-directory-b2c/active-directory-b2c-tutorials-web-api)
* [Azure AD B2C: Call an ASP.NET Web API from an ASP.NET Web App](https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi) (code sample)

If you start with a fresh clone of the sample and follow the steps in those tutorials, you should be able to sign-up/sign-in/sign-out/profile edit, and use the To-Do List when using your own B2C tenant (not just the demo `fabrikamb2c` tenant).

**Comment by jennyf19** [comment]
closing @kodubeau please reopen if what @mmacy posted above is not sufficient or you still have issues. Thanks.
