### ISSUE TITLE
ConfidentialClientApplication.Users is obsolete

### ISSUE THREAD

**Issue by aai2on** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#50]
Latest version with libraries updated as of 1/27/2019 this demo no longer works.

**ClientApplicationBase.Users is obsolete  - Use GetAccountesAsync instead**

ConfidentialClientApplication cca = new ConfidentialClientApplication(Startup.ClientId, Startup.Authority, Startup.RedirectUri, new ClientCredential(Startup.ClientSecret), userTokenCache, null);

**Comment by vovanb** [comment]
any fixes?

**Comment by TiagoBrenck** [comment]
The replacement for `Users` is `IAccount`. The code snippet using it in this sample can be found on TaskController.cs:

```c#
IConfidentialClientApplication cca = MsalAppBuilder.BuildConfidentialClientApplication();
var accounts = await cca.GetAccountsAsync();
AuthenticationResult result = await cca.AcquireTokenSilent(scope, accounts.FirstOrDefault()).ExecuteAsync();
```

**Comment by jennyf19** [comment]
closing as answered.
