### ISSUE TITLE
OAuthBearerAuthenticationOptions in .NET 4.6 with Azure AD v2

### ISSUE THREAD

**Issue by jrmcdona** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#52]
Do you guys have a sample in .NET 4.6 or can give a pointer?

IIssuerSecurityTokenProvider is not longer available in Microsoft.Owin.Security.Jwt. There is now IIssuerSecurityKeyProvider and OpenIdConnectCachingSecurityTokenProvider is no longer compiling.

Therefore I cannot get OAuthBearerAuthenticationOptions working with an Azure AD v2 endpoint on my Web API.

**Comment by alex-lucid** [comment]
Same here, any updates?

**Comment by jrmcdona** [comment]
** here is the convo I had elsewhere **

That’s outdated, it should look something like this now:
https://github.com/aspnet/AspNetKatana/blob/e2b18ec84ceab7ffa29d80d89429c9988ab40144/src/Microsoft.Owin.Security.ActiveDirectory/WsFedCachingSecurityKeyProvider.cs#L18

Thanks, so is that now built in or do I need to essentially take WsFedCachingSecurityKeyProvider and use it like OpenIdConnectCachingSecurityTokenProvider which gets manually added as a class to the project?

You need to update OpenIdConnectCachingSecurityTokenProvider and model it after WsFedCachingSecurityKeyProvider.

** I never finished getting it working and didn't move forward with MSAL **

**Comment by jmprieur** [comment]
Closing as this issue is very old and the sample was updated since;
