### ISSUE TITLE
MSALPerUserSessionTokenCache not correctly persisting tokencache

### ISSUE THREAD

**Issue by tmjacobs** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#56]
The logic for UserTokenCacheBeforeAccessNotification and UserTokenCacheAfterAccessNotification has been swapped.  the code should load the cache before access and persist after access.  Simply swapping the code inside the methods fixed this problem for me.

**Comment by TiagoBrenck** [comment]
@tmjacobs could you please give more information about what problem did you face?
I believe that your suggestion to swipe the order might not be accurate. So please give us more details and we will be glad to help you. 

Thanks

**Comment by tmjacobs** [comment]
No accounts were being returned when I used session cache.  When I used memory cache, the correct account was returned from cached.  When I compared the session cache to the memory cache, I noticed that the load and persist code was switched.  I changed the session cache to match the memory cache and the session cache then correctly returned the correct account.

**Comment by TiagoBrenck** [comment]
Oh now I got what you mean. I will open a PR with the fix.
Thanks for pointing that out.
