### ISSUE TITLE
Why does OpenIdConnectCachingSecurityTokenProvider.cs use locks

### ISSUE THREAD

**Issue by brentschmaltz** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#58]
ConfigurationManager returns a OpenIdConnectConfiguration object where all properties represent a single consistent view.

What is the purpose of this object: OpenIdConnectCachingSecurityTokenProvider?

**Comment by jennyf19** [comment]
Please use this more current [b2c sample](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C)

closing.
