### ISSUE TITLE
Feature request: Simplified sample project

### ISSUE THREAD

**Issue by InfoHunt** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#62]
Dear all, 
First, thanks a mil for providing the sample application and the code-along sections attached to this project. The code-along sections helped a lot in the initial phase. However, what I did not quite grasp was why you decided to spread the sample application across multiple projects including making use of partial classes?
While the sample on its own is really great, I found it hard to apply the principles laid out in the sample to already existing projects that require implementation of Azure B2C features such as Login via Azure. I am currently struggling with such an undertaking (since an update via VS2019 using Connected Services failed). 

Would it thus be possible to either provide a simplified version of the present project or maybe even an extra section describing how to add Azure B2C features to an existing solutions? I figure this would be beneficial to the community and to the project as such. I am sorry if this request is a lot to ask but being a beginner, I've been having difficulties once I completed the code-along section. 

Please do not hesitate to get in touch in case my question is unclear (or in case I missed something, I haven't done much forum posting so far). I am looking forward to any reply. Thanks a mil in advance, kind regards.

IH

**Comment by mmacy** [comment]
@InfoHunt I wholeheartedly agree with your request:

> provide a simplified version of the present project or maybe even an extra section describing how to add Azure B2C features to an existing solutions

What I believe we need, in addition to the end-to-end, full-fledged samples that we already have (like this one), are companion "quickstart" samples. Such quickstart samples would include only the very minimum code modifications to a default template that are required to integrate B2C. While these smaller, more simplified samples might not present a production-ready example, it would help those new to the service and perhaps even to ASP.NET Core understand exactly what the need to add, and where. The goal would be to not have to tediously parse and unwind code which might typically be used in a production application just to get the bits you really need, and then have to figure out how to integrate it into your own app.

Such "quickstart" samples would help with adding B2C support to new as well as existing applications. We'd then add or update our existing quickstarts on docs.microsoft.com to walk the reader through scaffolding the app/API, installing the correct package, and then discuss the primary tasks and their accompanying code snippets. An example of such a quickstart is the [Azure blob storage .NET quickstart](https://docs.microsoft.com/azure/storage/blobs/storage-quickstart-blobs-dotnet).

@InfoHunt, feel free to pile on any additional thoughts you have on what you'd like to see in a more simplified sample and accompanying documentation.

@jmprieur @jennyf19 @rayluo FYI, something I'd like to pitch to you all.

**Comment by InfoHunt** [comment]
@mmacy Thanks a mil for reply and the idea of introducing quickstart samples. My main issue with the current sample is that, at least for me as a beginner, there is a lot of code involved that is sort of "distracting" and it is difficult to figure out, which parts are required for which sign-up. I figure, a small  sample that would outline just how to set up an application login via Azure B2C is what I am currently looking for, e.g.
* how to configure an application to login using just Azure B2C
* what to bear in mind when you hook up your application to your Azure AD B2C tenant(s)
* screenshots (What you should see)
* a section describing the most frequent errors (optional: how to resolve the issues)

I'd be delighted adding more thoughts. Please do get in touch if there is new stuff to read and try out.

**Comment by jmprieur** [comment]
@InfoHunt : would something like this (which is for AAD) be closer to what you need? https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-1-MyOrg

**Comment by InfoHunt** [comment]
@jmprieur Thanks a mil for the link you provided. In terms of structure let's say "scope", this is already pretty close. I like the idea of having individual folders for each step/topic.

**Comment by jmprieur** [comment]
@InfoHunt @mmacy 
BTW, there is also a sign-in with B2C chapter there (https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-5-B2C), and we are working on Web app calls Web API (B2C): PR is https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/pull/192

cc: @jennyf19

**Comment by mmacy** [comment]
@InfoHunt Great feedback, thank you! On **this item** (screenshots), do you mean screenshots of expected output of the sample application, the app registration settings in the Azure portal, or both?

> * how to configure an application to login using just Azure B2C
> * what to bear in mind when you hook up your application to your Azure AD B2C tenant(s)
> * **screenshots (What you should see)**

We tend to shy away from including Azure portal UI screenshots as they get out of date extremely quickly, and thus often provide an even worse experience when the UI doesn't match the image. However, open to hearing your thoughts on this.

**Comment by InfoHunt** [comment]
@mmacy Thanks a mil for your reply. Sorry for not being precise when mentioning the screenshots. I was hinting at screenshots from within the application. This might be a personal preference, but it does help a lot to have some sort intermediary result (or at least a picture) if one has completed a step in creating/extending an application or working with a code sample. That is more or less what I was thinking. I hope could clarify this item. Please do feel free to get back in touch if there are still some thoughts that require clarification.

**Comment by mmacy** [comment]
@InfoHunt Yup, that answers it, and is in line with what I was thinking, as well. Thanks again for your feedback, it really does help us dial in a better format for our getting started material.

**Comment by InfoHunt** [comment]
@mmacy Glad I could help and thanks a mil for considering my suggestions, I wasn't sure in the beginning if taking a direct approach and creating a post was the way to go, since who am I to tell the pros what their documentation should look like. Do keep me posted about new content, I would enjoy reading through new stuff.

**Comment by InfoHunt** [comment]
Just a thought for a future "what might go wrong" section. Well, I do not know how what the sample might look like, but it might be worth adding what I have been struggling with.  My current issue is that when clicking on my sign-in button, I get a 404  with the Azure B2C URL being messed up, i.e. 
````
https://[company].b2clogin.com/[company].onmicrosoft.com//v2.0/.well-known/openid-configuration/v2.0/.well-known/openid-configuration'.]
````
I have been unable to locate where the URL is being rewritten, since the URL was fine in both `_metadataEndpoint` and `MetadataAddress` in the `Startup-cs` class. A more thorough description can be read here: https://bit.ly/34U9nab, although I had to edit the original post. Maybe you'll find the issues laid out there helpful in terms of how some might approach the task of adding Azure B2C. If you also could provide an answer I'd be even more delighted.

**Comment by jennyf19** [comment]
@InfoHunt Thanks. i believe you're the not the first dev to report this. i will take a look. I have made a separate issue to track this, which is linked above.

**Comment by jennyf19** [comment]
@InfoHunt we have a more current [b2c sample](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C) that you might be interested in.

I'm not sure if @mmacy has any follows-up from the above conversation, but I don't think we'll be making changes to this specific sample. You are welcome to submit a PR, if you like.
