### ISSUE TITLE
Sample is missing link to call password reset and profile editting policies

### ISSUE THREAD

**Issue by bachoang** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#66]
The Web App sample is missing links to call the following Function to reset password and profile editing policies

https://localhost:44316/Account/ResetPassword
https://localhost:44316/Account/EditProfile

while this guidance shows the screen shot having those links:
https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-quickstarts-web-app

**Comment by jennyf19** [comment]
@bachoang we support those policies in the code, so maybe they are just not showing up in the UI? i'll take a look.

**Comment by jennyf19** [comment]
@bachoang ....I see the edit profile/password reset buttons in the UI:
![image](https://user-images.githubusercontent.com/19942418/68722213-a10e5f00-0569-11ea-9051-050cd10de26e.png)

**Comment by jennyf19** [comment]
Click on the signed-in user's name to get the options for edit profile & reset password.

closing...fyi @bachoang
