### ISSUE TITLE
Issue with Redirect Url in host Azure AD Application

### ISSUE THREAD

**Issue by raiderjakk** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#67]
The reply URL for making your own application didn't work for me.  I had to consult this page.  If you look to the closed issues there is an entry for the redirect URL not working.  Once I 

https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-add-identity-providers#feedback

"None of the redirect URLs work
None of these worked as a redirect URL:

https://your-B2C-tenant-name.b2clogin.com/your-B2C-tenant-name.onmicrosoft.com/oauth2/authresp
https://{your-tenant-name}.b2clogin.com/{your-tenant-id}/oauth2/authresp
https://{your-tenant-name}.b2clogin.com/{your-tenant-name}.onmicrosoft.com/oauth2/authresp
But using Fiddler, I figured out this worked:

https://login.microsoftonline.com/te/{your-tenant-name}.onmicrosoft.com/oauth2/authresp"

I don't know if you have to update the sample.  The issue is closed by the admin but I still ran into this.

Thanks!

**Comment by TiagoBrenck** [comment]
Hi @raiderjakk could you help me find in the sample where are we suggesting to set the reply URL to those that didn't work?

**Comment by TiagoBrenck** [comment]
Closing since we haven't heard back from the user. Feel free to re-open if the error persists.
