### ISSUE TITLE
Custom Policies&KMSI: Password Reset and Cancel Sign up redirect to authentication response url without authenticating

### ISSUE THREAD

**Issue by sergiosolorzano** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#69]
I use this example for a B2C web app/web api authentication/authorisation. I also use Local Account [custom policies](https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-policy-get-started?tabs=app-reg-preview#create-the-signing-key) and [KMSI](https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-policy-keep-me-signed-in).

The issue I have is that in the case when a user clicks on forgot password->web app picks up the error->redirects to authentication response URL without authentication: here's the issue raised with images https://stackoverflow.com/questions/60870810/azure-custom-policies-kmsi-password-reset-and-cancel-sign-up-redirect-to-authe

I have re-done the web app/web api example adding the web.config changes but the issue remains.

thank you for your help

**Comment by sergiosolorzano** [comment]
Did someone come accross this issue before?

**Comment by TiagoBrenck** [comment]
If you set a breakpoint  where you are capturing the error code AADB2C90091 or AADB2C90118, does it get hit? Is your AccountController decorated with [AllowAnnonymous]?

**Comment by jmprieur** [comment]
Closing as there was no answer
