### ISSUE TITLE
Unable to authenticate to API & access to-do list function of application

### ISSUE THREAD

**Issue by monty-dev** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#7]
I am having issues starting the sample application and accessing the To Do List section of the app.

The error I receive is -
We're having trouble signing you in.
Error. Status code = InternalServerError

I am able to login to the application successfully, but not able to access the to do list function. 
I think the issue stems from the PublishedScopes. In the documentation, it does not tell which scopes should be created in the API to the web app, and there are no default values. I created values 'read','write','user_impersonation' and granted the web app access but this did not resolve my issue. 

TaskService web.config 
```
<appSettings>
    <add key="webpages:Version" value="3.0.0.0" />
    <add key="webpages:Enabled" value="false" />
    <add key="ClientValidationEnabled" value="true" />
    <add key="UnobtrusiveJavaScriptEnabled" value="true" />
    <add key="ida:AadInstance" value="https://login.microsoftonline.com/{0}/v2.0/.well-known/openid-configuration?p={1}" />
    <add key="ida:Tenant" value="montelb2c.onmicrosoft.com" />
    <add key="ida:ClientId" value="0340d8fc-1c37-4bc5-818c-28acfef6feee" />
    <add key="ida:SignUpSignInPolicyId" value="B2C_1A_signup_signinwithAAD" />

    <!-- The following settings is used for requesting access tokens -->
    <add key="api:ReadScope" value="read" />
    <add key="api:WriteScope" value="write" />
  </appSettings>

```
TaskWebApp web.config. 
   ```
<appSettings>
    <add key="webpages:Version" value="3.0.0.0" />
    <add key="webpages:Enabled" value="false" />
    <add key="ClientValidationEnabled" value="true" />
    <add key="UnobtrusiveJavaScriptEnabled" value="true" />
    <add key="ida:Tenant" value="montelb2c.onmicrosoft.com" />
    <add key="ida:ClientId" value="b4b2384b-457d-4fa6-a9ff-953f1834be8e" />
    <add key="ida:ClientSecret" value="hidden" />
    <add key="ida:AadInstance" value="https://login.microsoftonline.com/tfp/{0}/{1}/v2.0/.well-known/openid-configuration" />
    <add key="ida:RedirectUri" value="https://localhost:44316/" />
    
    <add key="ida:SignUpSignInPolicyId" value="B2C_1A_signup_signinwithAAD" />
    <add key="ida:EditProfilePolicyId" value="B2C_1A_ProfileEdit" />
    <add key="ida:ResetPasswordPolicyId" value="B2C_1A_PasswordReset" />
    
    <!-- Uncomment the localhost url if you want to run the API locally -->
    <!--add key="api:TaskServiceUrl" value="https://aadb2cplayground.azurewebsites.net/" /-->
    <add key="api:TaskServiceUrl" value="https://localhost:44332/" />

    <!-- The following settings is used for requesting access tokens -->
    <add key="api:ApiIdentifier" value="https://montelb2c.onmicrosoft.com/tasks" />
    <add key="api:ReadScope" value="read" />
    <add key="api:WriteScope" value="write" />
    
  </appSettings>
```

Please assist!

**Comment by parakhj** [comment]
"I created values 'read','write','user_impersonation' and granted the web app access"

That part seems to be correct. You also modified the ApiIdentifier in the code, which is good. There isn't anything else you need to configure. Are you sure your service is running on localhost:44332?

**Comment by lla23** [comment]
Have you found the issue? I'm experiencing the same, and also on Azure webapps, so it can't be the localhost service. This seems to me like a bug or performance issue of aad b2c.

**Comment by nabilshams** [comment]
I had similar issue when I realized that "My Test ASP.NET Web Application | API permissions" has not been granted the permission for read & write API. Make sure that you have granted those permissions. 

Debug the web application and make sure that you have received access token inside OnAuthorizationCodeReceived of Startup.Auth.cs.

**Comment by benphunter** [comment]
I also had the same issue and realised that I had made a mistake when reading the instructions. I granted API permissions in the webapp not the webapi. I need to pay more attention, hopefully this will help someone else.

**Comment by aremo-ms** [comment]
@jmprieur can we close it? Trying to cleanup and sort issues

**Comment by jmprieur** [comment]
Thanks for the heads-up and for helping cleaning-up @aremo-ms
