### ISSUE TITLE
Claims page work, but Todo List raises an error

### ISSUE THREAD

**Issue by artem-korolev** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#71]
Hi,

Authentication with login/signup link works okay. Claims page is also okay and shows my user information.
But To-Do List page raises this error:

```
Error.
We're having trouble signing you in.
Error reading to do list: An error occurred while sending the request
```

I tried to run solution in single project mode, and multiply project run more. Same result.
Original configuration, no changes

**Comment by artem-korolev** [comment]
```
Exception thrown: 'Microsoft.Identity.Client.MsalUiRequiredException' in Microsoft.Identity.Client.dll

Exception thrown: 'System.Net.Http.HttpRequestException' in mscorlib.dll
```

**Comment by TiagoBrenck** [comment]
Hi @artem-korolev, just to clarify your statement about running the solution using single vs multiple projects, this sample requires **both** projects to be running simultaneously. Running just one of them wont work.

Do you have a B2C tenant where you can register the web app and web api application using your own tenant? And then updating the web.configs to the correct values of your own registration? 

We are having troubles with the pre-configured web api application in our playground b2c tenant. Sorry about that.

**Comment by artem-korolev** [comment]
Hi @TiagoBrenck, everything works very well with playground tenent for me. at least right now. I just didn't proceed with **comment line 27 and uncomment line 28**

Everything works well now. Thank you very much!
