### ISSUE TITLE
Azure AD B2C not working on below sample when sign in button on home page is changed to an ajax call

### ISSUE THREAD

**Issue by InfoZone** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#72]
Our team has taken the sample and it works 100% as it is. We then wanted to change it to fit into the app we are building.
The main difference is is that the sign in button on our app, does an ajax all into another controller to start the sign in process.

Once this is clicked, it follows the same server side code as the original sample, but we get a CORS issue
Access to XMLHttpRequest at 'https://app.com/app.onmicrosoft.com/b2c_1_susi/oauth2/v2.0/authorize?' (redirected from 'https://localhost:44316/Account/SignUpSignIn') from origin 'https://localhost:44316' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

The main problem here is the login screen sits in one solution and the controller that the ajax call calls, sits in another dll.
![image](https://user-images.githubusercontent.com/17723426/89504194-f2c9da00-d7c7-11ea-9d2c-4655368b45cb.png)

calls the below 
![image](https://user-images.githubusercontent.com/17723426/89504164-e5145480-d7c7-11ea-8d60-8fd5f884ba2e.png)

**Comment by jmprieur** [comment]
See this sample to understand how to proceeed with Ajax calls: https://github.com/AzureAD/microsoft-identity-web/tree/master/tests/AjaxCallActionsWithDynamicConsent
