### ISSUE TITLE
Issue of "Unauthorized"

### ISSUE THREAD

**Issue by komiyasa** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#73]
I followed tutorial but I have following issue. How can I resolve it?
![image](https://user-images.githubusercontent.com/53052635/89971538-738c4880-dc96-11ea-929b-a6e223eb86e8.png)

**Comment by jmprieur** [comment]
This requires more information.
@komiyasa : proposing to close this issue as this is pretty old, but feel free to reopen if you still have the problem
