### ISSUE TITLE
facing issue while  uisng authorization_code

### ISSUE THREAD

**Issue by som-nitjsr** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#8]
{"error":"invalid_grant","error_description":"AADB2C90085: The service has encountered an internal error. Please reauthenticate and try again.\r\nCorrelation ID: 4810f417-400c-4410-a312-00f528dd4490\r\nTimestamp: 2017-06-26 13:53:28Z\r\n"}

**Comment by parakhj** [comment]
Just to verify that you didn't accidentally delete an app required for B2C to work, can you:

1.	Go to your Azure AD B2C tenant, and in the very left hand navigation, click on the arrow for “More services”.
2.	Search for and click on “App registrations”
3.	Double check to see if you have an app that starts with “b2c-extensions-app”

**Comment by som-nitjsr** [comment]
thnx it worked.

**Comment by parakhj** [comment]
Out of curiosity,  do you know how the app got deleted?

**Comment by som-nitjsr** [comment]
not sure how it got deleted.
