### ISSUE TITLE
Session never expires

### ISSUE THREAD

**Issue by rajoo8** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#81]
Hi Team,

I am using Azure B2C & setting Token lifetime to 5 mins & Session lifetime to “Rolling” & 15 mins.

I tested the above B2C setup with this sample app, however the session never expires.
Is this a issue with this sample app or am I missing anything else?

**Comment by jmprieur** [comment]
The session time is determined by the session token.
