### ISSUE TITLE
IDX10501: Signature validation failed. Unable to match keys

### ISSUE THREAD

**Issue by jasonfritts** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#91]
It should be noted that this sample code by default only supports verifying the token signatures of multiple policies (signup, profile edit, password reset etc), if all those policies are configured to use the same token signing key.  

Otherwise, if one policy is using a different token signing key you will get the error:
IDX10501: Signature validation failed. Unable to match keys

For instance, this means that you can't use a custom policy for signupsignin, and then a built in user flow policy for profile edit.  As custom policies and user flows will always have different token signing keys.

**Comment by jmprieur** [comment]
@jasonfritts I think you've answered your own question?

**Comment by jasonfritts** [comment]
I agree, but I think this behavior should be noted in the sample readme for those unfamiliar with signature validation only working if the same key is used across all policies.  It took a support case and investigation to find this was our issue due to using a user flow for sign in, but a custom policy for profile edit.

**Comment by aremo-ms** [comment]
@jasonfritts Readme.md was updated under "Known issues" section.
