### ISSUE TITLE
The Web App is 4 year old tech

### ISSUE THREAD

**Issue by 274188A** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#95]
Please update the web app to at a least .dotnet 3.1  asp.net core 

- the current web app is a bit of a museum piece :-)
thanks!

**Comment by jmprieur** [comment]
There is another sample for this, @274188A:
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C.
It's for 3.1, but if you change the framework to net5.0 this also works

Unfortunately we still have plenty of customers and partners who are still on ASP.NET classic ...

**Comment by aremo-ms** [comment]
@jmprieur may we close this issue?

**Comment by jmprieur** [comment]
Thanks for the heads-up, @aremo-ms
