### ISSUE TITLE
could not find file webapp-b2c-dotnet.dll

### ISSUE THREAD

**Issue by piqa2MS** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#98]
when i try to run the code i received this error "could not find file"  webapp-b2c-dotnet.dll" . how do i get this file? i checked the path and yes its empty. 
![error](https://user-images.githubusercontent.com/87461373/125730078-cad17040-fff2-46ef-be2e-5d02a31d8f10.jpg)

**Comment by jmprieur** [comment]
It could be because of Windows path size limitation @piqa2MS 
did you try to clone the repo close to the root of your hard drive? or rename the name of the folder to be smaller?

**Comment by piqa2MS** [comment]
> It could be because of Windows path size limitation @piqa2MS
> did you try to clone the repo close to the root of your hard drive? or rename the name of the folder to be smaller?

when i clone from github its under c:\users\<username>. so what u meant is by right when i clone it the webapp-b2c-dotnet.dll should be in the path mentioned in the error screenshot?

**Comment by jmprieur** [comment]
I mean, move the cloned folder to C:\gh\tinyname

**Comment by piqa2MS** [comment]
> I mean, move the cloned folder to C:\gh\tinyname

hi my issue is resolved. tq for your help.

**Comment by jmprieur** [comment]
Thanks for the update, @piqa2MS
