### ISSUE TITLE
trouble signing in - The reason phrase must not contain new-line characters.

### ISSUE THREAD

**Issue by piqa2MS** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#99]
when i login i can see id_token but do display name appear and when i click to-do list i got this error 
![error2](https://user-images.githubusercontent.com/87461373/125883030-d2c82199-a471-45f6-bfe0-de3c3a08cd2c.jpg)

**Comment by jmprieur** [comment]
did you configure your own B2C tenant, @piqa2MS ?

**Comment by piqa2MS** [comment]
> did you configure your own B2C tenant, @piqa2MS ?

yes. i use my own tenant

**Comment by jmprieur** [comment]
@piqa2MS : there are conditions for the cache to work. See https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/AAD-B2C-specifics#known-issue-with-azure-b2c

**Comment by bgavrilMS** [comment]
Assuming this was solved. Please reopen if not.
